name: Drone Telemetry Simulator

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  run-simulator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install pymongo

      - name: Run Simulator
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python python New_simulator.py